language: node_js
node_js:
  - "iojs"
  - "0.11"
  - "0.10"
before_install:
  - "npm install -g mocha crc-32 benchmark ansi"
  - "npm install blanket"
  - "npm install coveralls mocha-lcov-reporter"
after_success:
  - "make coveralls-spin"
  - "make perf-all"
